name: Build Voro-Emscripten

on:
  pull_request:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: mymindstorm/setup-emsdk@v14

      - name: Verify Emscripten is Installed
        run: emcc -v

      - name: Linux - Build Base Binary
        if: runner.os == 'Linux'
        run: ./build.sh

      - name: Linux - Upload Build
        uses: actions/upload-artifact@v4
        if: runner.os == 'Linux'
        with:
          name: Voro-Emscripten
          path: |
            ./README.md
            ./bin
